/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IEpDownload: typeof import('~icons/ep/download')['default']
  const IEpHouse: typeof import('~icons/ep/house')['default']
  const IEpPointer: typeof import('~icons/ep/pointer')['default']
  const IEpRefreshLeft: typeof import('~icons/ep/refresh-left')['default']
}
